# Generated by Django 5.2.7 on 2025-11-06 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='features',
            field=models.TextField(help_text='List of features included in this plan (deprecated - use plan_features instead)'),
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-check', 'fa-dumbbell')", max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_highlighted', models.BooleanField(default=False, help_text='Show this feature prominently')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='core.membershipplan')),
            ],
            options={
                'verbose_name': 'Plan Feature',
                'verbose_name_plural': 'Plan Features',
                'ordering': ['order', 'id'],
            },
        ),
    ]
