# Generated by Django 5.2.7 on 2025-11-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_membershipplan_features_planfeature'),
        ('workouts', '0003_workout_is_free_alter_workout_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='duration',
            field=models.CharField(choices=[('trial', 'Free Trial (1 week)'), ('1_week', '1 Week'), ('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('12_months', '12 Months')], default='1_month', help_text='Subscription duration', max_length=20),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='included_workouts',
            field=models.ManyToManyField(blank=True, help_text='Workouts included with this membership plan', related_name='membership_plans', to='workouts.workout'),
        ),
    ]
