# Generated by Django 5.2.7 on 2025-11-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workoutplan_userworkoutplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='is_free',
            field=models.BooleanField(default=False, help_text='If checked, this workout is free for all users'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='category',
            field=models.CharField(choices=[('chest', 'Chest'), ('shoulder', 'Shoulder'), ('back', 'Back'), ('legs', 'Legs'), ('arms', 'Arms'), ('abs', 'Abs'), ('full_body', 'Full Body'), ('cardio', 'Cardio'), ('strength', 'Strength Training'), ('flexibility', 'Flexibility'), ('hiit', 'HIIT'), ('yoga', 'Yoga'), ('pilates', 'Pilates'), ('other', 'Other')], max_length=20),
        ),
    ]
