# Generated by Django 5.2.7 on 2025-11-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workout_is_free_alter_workout_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='duration',
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.IntegerField(default=1, help_text='Number of sets'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='difficulty_level',
            field=models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3')], default='1', max_length=20),
        ),
    ]
