# Generated by Django 5.2.7 on 2025-11-13 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclass',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether this class requires payment'),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='location_details',
            field=models.TextField(blank=True, help_text='Specific location info (address, zoom link, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='location_type',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', help_text='Where the class is held', max_length=10),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in rupees (required if paid)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(help_text='Legacy field - use class_schedule for specific date/time'),
        ),
        migrations.AlterField(
            model_name='gymclass',
            name='schedule_days',
            field=models.CharField(blank=True, help_text='Legacy field - use ClassSchedule for specific dates/times', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gymclass',
            name='schedule_time',
            field=models.TimeField(blank=True, help_text='Legacy field - use ClassSchedule for specific dates/times', null=True),
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateField()),
                ('class_time', models.TimeField()),
                ('max_capacity', models.IntegerField(blank=True, help_text='Override class default capacity if needed', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='bookings.gymclass')),
            ],
            options={
                'verbose_name_plural': 'Class Schedules',
                'ordering': ['class_date', 'class_time'],
                'unique_together': {('gym_class', 'class_date', 'class_time')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='class_schedule',
            field=models.ForeignKey(blank=True, help_text='Specific class schedule (preferred)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.classschedule'),
        ),
    ]
